grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 3

model_selection:
  module_0:
    class: CatBoostClassifier
    module: catboost
    params: {}
    search_param_grid:
      iterations:
      - 100
      - 200
      - 300
      learning_rate:
      - 0.01
      - 0.05
      - 0.1
      depth:
      - 4
      - 6
      - 8
      l2_leaf_reg:
      - 1
      - 3
      - 5
      border_count:
      - 32
      - 64
      - 128
      verbose:
      - 0

      
  module_1:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
      n_estimators: 50
      max_depth":  10
      max_features: sqrt
      min_samples_split: 2
      min_samples_leaf: 1
      bootstrap: True
    search_param_grid:
      n_estimators: 
      - 50 
      - 100 
      - 200
      max_depth: 
      - 10 
      - 20 
      max_features: 
      - sqrt 
      - log2 
      min_samples_split: 
      - 2 
      - 5 
      - 10
      min_samples_leaf: 
      - 1 
      - 2
      - 4
      bootstrap: 
      - True 
      - False
